Allow running validations passed as argument

diff --git a/ansible-tests/mistral/run-validation b/ansible-tests/mistral/run-validation
--- a/ansible-tests/mistral/run-validation
+++ b/ansible-tests/mistral/run-validation
@@ -1,8 +1,20 @@
 #!/bin/bash
 
-# NOTE: place this at: /usr/local/bin/run-validation
+set -e
 
-set -ex
+VALIDATION=$1
+DYNAMIC_INVENTORY_SCRIPT=/usr/share/tripleo-validations/tripleo-ansible-inventory.py
+
+if [[ -z "$VALIDATION" ]]; then
+    echo "Missing required validation name"
+    exit 1
+fi
+
+VALIDATION_FILE=/usr/share/tripleo-validations/validations/${VALIDATION}.yaml
+if [[ ! -r "$VALIDATION_FILE" ]]; then
+    echo "Can not find validation at $VALIDATION_FILE"
+    exit 1
+fi
 
 echo Sourcing stackrc
 source /home/stack/stackrc
@@ -12,8 +24,6 @@ source /home/stack/stackrc
 export ANSIBLE_HOST_KEY_CHECKING=False
 
 echo Running validation
-# TODO(mandre) run the validation passed as argument
-ansible-playbook -i /usr/share/tripleo-validations/tripleo-ansible-inventory.py \
-  /usr/share/tripleo-validations/validations/haproxy.yaml
+ansible-playbook -i $DYNAMIC_INVENTORY_SCRIPT $VALIDATION_FILE
 
 echo Validation finished
